export * from './Acerca';
export * from './ClaseDetalle';
export * from './Clases';
export * from './Contacto';
export * from './Home';
export * from './Horario';
export * from './Precios';
export * from './Profesores';
export * from './ProfesoresInfo';
